version: "3.7"
services:
#  app:
#    build:
#      args:
#        user: jsantana
#        uid: 1000
#      context: ./
#      dockerfile: Dockerfile
#    container_name: laravel-jsantana-app
#    restart: unless-stopped
#    working_dir: /var/www/html
#    volumes:
#      - ./src:/var/www/html
#    networks:
#      - laravelnet
#    depends_on:
#      - mysql
#      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravelnet
    depends_on:
      - php
      - mysql


  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravelnet


  php:
    build:
      args:
        user: jsantana
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge
